//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I18NExample {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I18NExample.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Button.
        /// </summary>
        internal static string BPButton {
            get {
                return ResourceManager.GetString("BPButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something.
        /// </summary>
        internal static string BPLabel {
            get {
                return ResourceManager.GetString("BPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP Code.
        /// </summary>
        internal static string CardCode {
            get {
                return ResourceManager.GetString("CardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP Name.
        /// </summary>
        internal static string CardName {
            get {
                return ResourceManager.GetString("CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string DocEntry {
            get {
                return ResourceManager.GetString("DocEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Label.
        /// </summary>
        internal static string Form1Label {
            get {
                return ResourceManager.GetString("Form1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My i18n Form.
        /// </summary>
        internal static string Form1Title {
            get {
                return ResourceManager.GetString("Form1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        internal static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Person Code.
        /// </summary>
        internal static string SlpCode {
            get {
                return ResourceManager.GetString("SlpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines1.
        /// </summary>
        internal static string UDOLines {
            get {
                return ResourceManager.GetString("UDOLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines2.
        /// </summary>
        internal static string UDOLines2 {
            get {
                return ResourceManager.GetString("UDOLines2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My UDO.
        /// </summary>
        internal static string UDOTitle {
            get {
                return ResourceManager.GetString("UDOTitle", resourceCulture);
            }
        }
    }
}
